name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - .vscode
      - LICENSE
      - README.md

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      CI: true
    name: Build and Deploy Job
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
